name: mechkonect
description: MECHKONECT - Connect vehicle owners in Uganda with vetted mechanics and emergency services.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.5+1
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  dio: ^5.9.0
  retrofit: ^4.9.0
  json_annotation: ^4.9.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.0.4
  google_sign_in: ^6.2.1
  google_maps_flutter: ^2.14.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  lottie: ^3.3.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.2
  lucide_icons_flutter: ^3.1.6
  go_router: ^17.0.0
  google_fonts: ^6.3.2
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.2
  permission_handler: ^12.0.1
  image_picker: ^1.2.1
  flutter_secure_storage: ^9.2.4
  workmanager: ^0.9.0+3
  uuid: ^4.5.2
  equatable: ^2.0.5
  flutter_paystack_plus: ^2.1.0
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  flutter_local_notifications: ^19.5.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.3
  json_serializable: ^6.11.1
  retrofit_generator: ^10.1.4
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/illustrations/
    - assets/lottie/

flutter_launcher_icons:
  android: true
  image_path: assets/icons/app_icon.png
